default: &default
  adapter: postgresql
  encoding: utf-8
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: god
  username: god
  password: god
  host: localhost

test:
  <<: *default
  database: god_test
  username: god
  password: god
  host: localhost
  
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  pool: 15
